const WORDS_BY_CATEGORY = {
  Cantantes: [
    ["Shakira", "Karol G"],
    ["Bad Bunny", "J Balvin"],
    ["Adele", "Taylor Swift"],
    ["Luis Fonsi", "Daddy Yankee"],
    ["Rihanna", "Beyoncé"],
    ["Dua Lipa", "Ariana Grande"],
    ["The Weeknd", "Bruno Mars"],
    ["Coldplay", "Imagine Dragons"],
    ["Ed Sheeran", "Sam Smith"],
    ["Rosalía", "C. Tangana"],
    ["Ozuna", "Anuel AA"],
    ["Maluma", "Prince Royce"],
    ["Marc Anthony", "Romeo Santos"],
    ["Juanes", "Carlos Vives"],
    ["Camilo", "Sebastián Yatra"],
    ["Nicky Jam", "Wisin"],
    ["Feid", "Ryan Castro"],
    ["Myke Towers", "Lunay"],
    ["Christina Aguilera", "Britney Spears"],
    ["Selena Gomez", "Miley Cyrus"],
    ["Harry Styles", "Zayn"],
    ["Post Malone", "Travis Scott"],
    ["Doja Cat", "Nicki Minaj"],
    ["Billie Eilish", "Lorde"],
    ["Katy Perry", "Lady Gaga"],
    ["Alejandro Sanz", "Pablo Alborán"],
    ["Shawn Mendes", "Charlie Puth"],
    ["Soda Stereo", "Héroes del Silencio"],
    ["Maná", "Enanitos Verdes"],
    ["Vicente García", "Monsieur Periné"]
  ],

  Famosos: [
    ["Messi", "Cristiano Ronaldo"],
    ["Elon Musk", "Jeff Bezos"],
    ["MrBeast", "Ibai"],
    ["Will Smith", "Chris Rock"],
    ["Tom Cruise", "Brad Pitt"],
    ["Leonardo DiCaprio", "Johnny Depp"],
    ["Dwayne Johnson", "John Cena"],
    ["Kim Kardashian", "Kylie Jenner"],
    ["Zendaya", "Emma Watson"],
    ["Robert Downey Jr.", "Chris Evans"],
    ["Scarlett Johansson", "Margot Robbie"],
    ["Keanu Reeves", "Ryan Gosling"],
    ["Taylor Lautner", "Robert Pattinson"],
    ["Jason Momoa", "Henry Cavill"],
    ["Jackie Chan", "Jet Li"],
    ["Vin Diesel", "Paul Walker"],
    ["Selena Gomez", "Ariana Grande"],
    ["Bad Bunny", "Peso Pluma"],
    ["Ibai", "AuronPlay"],
    ["Rubius", "Vegetta777"],
    ["MrBeast", "Logan Paul"],
    ["PewDiePie", "Markiplier"],
    ["KSI", "Jake Paul"],
    ["Shakira", "Jennifer Lopez"],
    ["Michael Jordan", "LeBron James"],
    ["Stephen Curry", "Kevin Durant"],
    ["Usain Bolt", "Michael Phelps"],
    ["Rafael Nadal", "Roger Federer"],
    ["Tiger Woods", "Phil Mickelson"],
    ["Serena Williams", "Venus Williams"]
  ],

  Películas: [
    ["Titanic", "Avatar"],
    ["Matrix", "Inception"],
    ["Gladiador", "Troya"],
    ["El Padrino", "Scarface"],
    ["Interestelar", "Gravity"],
    ["Jurassic Park", "King Kong"],
    ["Batman", "The Dark Knight"],
    ["Avengers", "Justice League"],
    ["Iron Man", "Spider-Man"],
    ["Star Wars", "Star Trek"],
    ["Harry Potter", "Fantastic Beasts"],
    ["El Señor de los Anillos", "El Hobbit"],
    ["Transformers", "Pacific Rim"],
    ["Toy Story", "Cars"],
    ["Buscando a Nemo", "Monsters Inc"],
    ["Frozen", "Moana"],
    ["Coco", "Encanto"],
    ["Up", "Wall-E"],
    ["Mad Max", "Fury Road"],
    ["Rocky", "Creed"],
    ["Terminator", "Robocop"],
    ["Alien", "Predator"],
    ["Piratas del Caribe", "La Momia"],
    ["Indiana Jones", "Uncharted"],
    ["Jumanji", "Ready Player One"],
    ["Matrix Reloaded", "Matrix Revolutions"],
    ["Avengers Endgame", "Infinity War"],
    ["Batman Begins", "The Batman"],
    ["Logan", "Deadpool"],
    ["El Origen", "Tenet"]
  ],

  "Personajes Públicos": [
    ["Barack Obama", "Donald Trump"],
    ["Joe Biden", "Kamala Harris"],
    ["Napoleón", "Julio César"],
    ["Simón Bolívar", "José de San Martín"],
    ["Abraham Lincoln", "George Washington"],
    ["Winston Churchill", "Franklin D. Roosevelt"],
    ["Vladimir Putin", "Xi Jinping"],
    ["Emmanuel Macron", "Angela Merkel"],
    ["Pedro Castillo", "Keiko Fujimori"],
    ["Nayib Bukele", "Andrés Manuel López Obrador"],
    ["Justin Trudeau", "Boris Johnson"],
    ["Nelson Mandela", "Desmond Tutu"],
    ["Mahatma Gandhi", "Jawaharlal Nehru"],
    ["Fidel Castro", "Che Guevara"],
    ["Hugo Chávez", "Nicolás Maduro"],
    ["Rafael Correa", "Lenín Moreno"],
    ["Michelle Bachelet", "Cristina Kirchner"],
    ["Lula da Silva", "Jair Bolsonaro"],
    ["María Corina Machado", "Leopoldo López"],
    ["José Mujica", "Tabaré Vázquez"],
    ["Eva Perón", "Isabel Perón"],
    ["Margaret Thatcher", "Theresa May"],
    ["Indira Gandhi", "Benazir Bhutto"],
    ["Yitzhak Rabin", "Shimon Peres"],
    ["Golda Meir", "Menachem Begin"],
    ["Francisco Franco", "Juan Carlos I"],
    ["Felipe VI", "Letizia Ortiz"],
    ["Papa Francisco", "Benedicto XVI"],
    ["Dalai Lama", "Panchen Lama"],
    ["Malala Yousafzai", "Greta Thunberg"]
  ],

  Juegos: [
    ["Dota 2", "League of Legends"],
    ["CS:GO", "Valorant"],
    ["Fortnite", "PUBG"],
    ["Minecraft", "Roblox"],
    ["GTA V", "Red Dead Redemption"],
    ["FIFA", "eFootball"],
    ["Call of Duty", "Battlefield"],
    ["Overwatch", "Paladins"],
    ["Apex Legends", "Warzone"],
    ["Among Us", "Fall Guys"],
    ["Clash Royale", "Clash of Clans"],
    ["Brawl Stars", "Mobile Legends"],
    ["Hearthstone", "Legends of Runeterra"],
    ["Skyrim", "The Witcher 3"],
    ["Elden Ring", "Dark Souls"],
    ["Diablo", "Path of Exile"],
    ["World of Warcraft", "Final Fantasy XIV"],
    ["Pokémon", "Digimon"],
    ["Zelda", "Genshin Impact"],
    ["Mario Kart", "Crash Team Racing"],
    ["God of War", "Assassin’s Creed"],
    ["Far Cry", "Just Cause"],
    ["Metal Gear Solid", "Splinter Cell"],
    ["Resident Evil", "Silent Hill"],
    ["Dead Space", "The Callisto Protocol"],
    ["Portal", "Half-Life"],
    ["Left 4 Dead", "Back 4 Blood"],
    ["Fallout", "Metro"],
    ["Hollow Knight", "Ori"],
    ["Celeste", "Dead Cells"]
  ],

  "Personajes de Videojuegos": [
    ["Mario", "Sonic"],
    ["Kratos", "Master Chief"],
    ["Link", "Zelda"],
    ["Geralt", "Ezio"],
    ["Lara Croft", "Nathan Drake"],
    ["Solid Snake", "Sam Fisher"],
    ["Cloud", "Sephiroth"],
    ["Bowser", "Dr. Eggman"],
    ["Donkey Kong", "Crash Bandicoot"],
    ["Ryu", "Ken"],
    ["Sub-Zero", "Scorpion"],
    ["Jin Kazama", "Kazuya Mishima"],
    ["Mega Man", "Samus Aran"],
    ["Kirby", "Yoshi"],
    ["Pikachu", "Charizard"],
    ["Ash", "Red"],
    ["Arthur Morgan", "John Marston"],
    ["Joel", "Ellie"],
    ["Aloy", "Lara Croft"],
    ["Eivor", "Kassandra"],
    ["Dante", "Vergil"],
    ["Bayonetta", "Jeanne"],
    ["Sora", "Riku"],
    ["Ratchet", "Jak"],
    ["Spyro", "Crash"],
    ["Cuphead", "Mugman"],
    ["Sans", "Papyrus"],
    ["Isaac", "The Lost"],
    ["Zagreus", "Thanatos"],
    ["Ori", "Naru"]
  ],

  Series: [
    ["Breaking Bad", "Better Call Saul"],
    ["Game of Thrones", "House of the Dragon"],
    ["The Walking Dead", "Fear the Walking Dead"],
    ["Stranger Things", "Dark"],
    ["La Casa de Papel", "Berlin"],
    ["Narcos", "El Chapo"],
    ["Peaky Blinders", "Boardwalk Empire"],
    ["Vikings", "The Last Kingdom"],
    ["The Boys", "Invincible"],
    ["The Mandalorian", "Andor"],
    ["The Witcher", "Wheel of Time"],
    ["Black Mirror", "Love Death & Robots"],
    ["Westworld", "Altered Carbon"],
    ["Lost", "From"],
    ["Dexter", "You"],
    ["Sherlock", "Lupin"],
    ["Friends", "How I Met Your Mother"],
    ["The Office", "Parks and Recreation"],
    ["Brooklyn Nine-Nine", "Superstore"],
    ["The Simpsons", "Family Guy"],
    ["South Park", "Rick and Morty"],
    ["Dragon Ball Z", "Dragon Ball Super"],
    ["Attack on Titan", "Tokyo Ghoul"],
    ["One Piece", "Naruto"],
    ["The Crown", "The Queen"],
    ["Wednesday", "Chilling Adventures of Sabrina"],
    ["Euphoria", "Skins"],
    ["Elite", "Gossip Girl"],
    ["House", "Grey’s Anatomy"],
    ["Chernobyl", "The Americans"]
  ],

  Animales: [
    ["León", "Tigre"],
    ["Águila", "Halcón"],
    ["Lobo", "Coyote"],
    ["Tiburón", "Orca"],
    ["Elefante", "Rinoceronte"],
    ["Gato", "Perro"],
    ["Pantera", "Jaguar"],
    ["Oso", "Polar"],
    ["Cebra", "Caballo"],
    ["Mono", "Chimpancé"],
    ["Serpiente", "Lagarto"],
    ["Cocodrilo", "Caimán"],
    ["Pingüino", "Foca"],
    ["Delfín", "Ballena"],
    ["Búho", "Lechuza"],
    ["Camello", "Dromedario"],
    ["Ratón", "Hámster"],
    ["Toro", "Búfalo"],
    ["Zorro", "Mapache"],
    ["Puma", "Lince"],
    ["Gorila", "Orangután"],
    ["Araña", "Escorpión"],
    ["Mariposa", "Polilla"],
    ["Abeja", "Avispa"],
    ["Pulpo", "Calamar"],
    ["Caracol", "Babosa"],
    ["Gallina", "Gallo"],
    ["Pato", "Ganso"],
    ["Cabra", "Oveja"],
    ["Vaca", "Bisonte"]
  ],

  "Lugares Famosos": [
    ["París", "Londres"],
    ["Nueva York", "Los Ángeles"],
    ["Roma", "Atenas"],
    ["Tokio", "Seúl"],
    ["Madrid", "Barcelona"],
    ["Lima", "Bogotá"],
    ["Río de Janeiro", "São Paulo"],
    ["Buenos Aires", "Montevideo"],
    ["Machu Picchu", "Chichén Itzá"],
    ["Petra", "Taj Mahal"],
    ["Dubái", "Abu Dabi"],
    ["Las Vegas", "Miami"],
    ["Venecia", "Florencia"],
    ["Berlín", "Múnich"],
    ["Ámsterdam", "Bruselas"],
    ["Lisboa", "Oporto"],
    ["Praga", "Viena"],
    ["Estambul", "Ankara"],
    ["El Cairo", "Alejandría"],
    ["Marrakech", "Casablanca"],
    ["Bangkok", "Phuket"],
    ["Sídney", "Melbourne"],
    ["Toronto", "Vancouver"],
    ["San Francisco", "Silicon Valley"],
    ["Hollywood", "Beverly Hills"],
    ["Cancún", "Tulum"],
    ["Cusco", "Arequipa"],
    ["Medellín", "Cartagena"],
    ["La Habana", "Varadero"],
    ["Punta Cana", "Santo Domingo"]
  ],

  Comida: [
    ["Pizza", "Hamburguesa"],
    ["Sushi", "Ramen"],
    ["Tacos", "Burritos"],
    ["Ceviche", "Tiradito"],
    ["Paella", "Risotto"],
    ["Asado", "Parrillada"],
    ["Pasta", "Lasaña"],
    ["Empanada", "Arepa"],
    ["Hot Dog", "Choripán"],
    ["Croissant", "Pain au Chocolat"],
    ["Helado", "Sorbete"],
    ["Brownie", "Cheesecake"],
    ["Donut", "Cupcake"],
    ["Panqueque", "Waffle"],
    ["Churros", "Buñuelos"],
    ["Pollo Frito", "Pollo Broaster"],
    ["Arroz Chaufa", "Arroz Frito"],
    ["Sopa Ramen", "Pho"],
    ["Hamburguesa Vegana", "Hamburguesa Clásica"],
    ["Ensalada César", "Ensalada Griega"],
    ["Pizza Margarita", "Pizza Pepperoni"],
    ["Nachos", "Quesadillas"],
    ["Curry", "Goulash"],
    ["Falafel", "Hummus"],
    ["Dim Sum", "Gyozas"],
    ["Tamales", "Hallacas"],
    ["Pupusas", "Gorditas"],
    ["Causa Limeña", "Papa a la Huancaína"],
    ["Lomo Saltado", "Tallarin Saltado"],
    ["Anticuchos", "Brochetas"]
  ]
};

export async function generateWords(category) {
  const options = WORDS_BY_CATEGORY[category];

  if (!options || options.length === 0) {
    return {
      palabra_real: "Messi",
      palabra_impostor: "Cristiano Ronaldo"
    };
  }

  const [palabra_real, palabra_impostor] =
    options[Math.floor(Math.random() * options.length)];

  return {
    palabra_real,
    palabra_impostor
  };
}
